### PR TITLE
Fix console drag-and-drop uploads

### LINKED ISSUE #1930: Drag-and-Drop files onto console no longer works
The functionality to be able to drop a file on the console and have it get transferred to the device doesn't seem to work in new or old UI.

Have't investigated yet. Frank reported and I confirmed that I had the same problem.

### PR DESCRIPTION
**Pull request by joshk**

### CODE REVIEW

File: assets/js/console.js [hunk 1]
```diff
@@ -251,40 +251,42 @@ dropzone.addEventListener(
   e => {
     e.preventDefault()
     e.stopPropagation()
-    e.dataTransfer.items.forEach(item => {
-      const file = item.getAsFile()
-      const reader = file.stream().getReader()
+    if (e.dataTransfer.items) {
```
Comment (nshoes) [inline assets/js/console.js:254]: Any ideas on what caused this to break?

**Review by nshoes — APPROVED** [review]

File: assets/js/console.js (hunk 1 above)
Comment (joshk) [reply assets/js/console.js:254]: From what I could tell, its that `e.dataTransfer.items.forEach` is the culprit. I don't think `forEach` is a method on `items`.

Comment (nshoes) [reply assets/js/console.js:254]: Ah, makes sense! Thanks.
