### PR TITLE
Issue #458: Add error handling when deleting firmware with associated deployments

### LINKED ISSUE #458: more gracious failure when attempting to delete firmware still tied to deployment
Right now if you try to delete a firmware tied to a deployment, it just crashes.

Instead, we should handle this Changeset error more graciously and turn it into a error flash message.

While we're at it, we should probably change the error from `deployment does not exist` to something more specific to this case since it is caused _because_ the deployment _does_ exist. Message could be something like "cannot delete firmware that has any deployments"

```elixir
error] #PID<0.2606.0> running NervesHubWWWWeb.Endpoint (connection #PID<0.2573.0>, stream id 11) terminated
Server: nerves-hub.org:4000 (http)
Request: POST /products/2642/firmware/delete/2441
** (exit) an exception was raised:
    ** (RuntimeError) expected action/2 to return a Plug.Conn, all plugs must receive a connection (conn) and return a connection, got: {:error, #Ecto.Changeset<action: :delete, changes: %{}, errors: [deployments: {"does not exist", [constraint: :foreign, constraint_name: "deployments_firmware_id_fkey"]}], data: #NervesHubWebCore.Firmwares.Firmware<>, valid?: false>}
        (nerves_hub_www) lib/nerves_hub_www_web/controllers/firmware_controller.ex:1: NervesHubWWWWeb.FirmwareController.phoenix_controller_pipeline/2
        (nerves_hub_www) lib/nerves_hub_www_web/endpoint.ex:1: NervesHubWWWWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:275: Phoenix.Router.__call__/1
        (nerves_hub_www) lib/nerves_hub_www_web/endpoint.ex:1: NervesHubWWWWeb.Endpoint.plug_builder_call/2
        (nerves_hub_www) lib/plug/debugger.ex:122: NervesHubWWWWeb.Endpoint."call (overridable 3)"/2
        (nerves_hub_www) lib/nerves_hub_www_web/endpoint.ex:1: NervesHubWWWWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:33: Phoenix.Endpoint.Cowboy2Handler.init/2
        (cowboy) /Users/jonjon/repos/nerves_hub_web/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /Users/jonjon/repos/nerves_hub_web/deps/cowboy/src/cowboy_stream_h.erl:296: :cowboy_stream_h.execute/3
        (cowboy) /Users/jonjon/repos/nerves_hub_web/deps/cowboy/src/cowboy_stream_h.erl:274: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

### PR DESCRIPTION
**Pull request by chazwatkins**
Closes #458 

Adds an error flash message when trying to delete a firmware that has associated deployments.

### CODE REVIEW

File: apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/firmware_controller.ex [hunk 1]
```diff
@@ -93,11 +93,18 @@ defmodule NervesHubWWWWeb.FirmwareController do
...
-      |> put_flash(:info, "Firmware successfully deleted")
-      |> redirect(to: Routes.firmware_path(conn, :index, org.name, product.name))
+    with {:ok, firmware} <- Firmwares.get_firmware_by_product_and_uuid(product, uuid) do
+      case Firmwares.delete_firmware(firmware) do
+        :ok ->
+          conn
+          |> put_flash(:info, "Firmware successfully deleted")
+          |> redirect(to: Routes.firmware_path(conn, :index, org.name, product.name))
+
+        {:error, %Ecto.Changeset{errors: [deployments: _]}} ->
```
Comment (jjcarstens) [inline apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/firmware_controller.ex]: Since this is a pretty specific match, we probably want one more to catch _all_ potential errors.

File: apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/firmware_controller.ex [hunk 2]
```diff
@@ -93,11 +93,18 @@ defmodule NervesHubWWWWeb.FirmwareController do
   end
 
   def delete(%{assigns: %{org: org, product: product}} = conn, %{"firmware_uuid" => uuid}) do
-    with {:ok, firmware} <- Firmwares.get_firmware_by_product_and_uuid(product, uuid),
-         :ok <- Firmwares.delete_firmware(firmware) do
-      conn
-      |> put_flash(:info, "Firmware successfully deleted")
-      |> redirect(to: Routes.firmware_path(conn, :index, org.name, product.name))
```
Comment (jjcarstens) [inline apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/firmware_controller.ex]: This is a super nit-pick, but we can probably just keep the `with` statement as is and add associated matching `else` clauses for the errors:

```elixir
with {:ok, firmware} <- Firmwares.get_firmware_by_product_and_uuid(product, uuid),
          :ok <- Firmwares.delete_firmware(firmware) do
  ...
else
  {:error, %Ecto.Changeset{errors: [deployments: _]}} ->
    ..
  {:error, e} ->
    ..
end
```

File: apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/firmware_controller.ex (hunk 1 above)
Comment (chazwatkins) [reply apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/firmware_controller.ex]: I've added the `catch-all` condition

File: apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/firmware_controller.ex (hunk 2 above)
Comment (chazwatkins) [reply apps/nerves_hub_www/lib/nerves_hub_www_web/controllers/firmware_controller.ex]: Reverted to the `with` as requested and added the `else` pattern matching for both deployments and catch-all.

**Comment by chazwatkins** [comment]
@jjcarstens Thanks for taking the time to review the contribution.

The requested changes have been implemented

1. Revert from `case` statement within the `with` to `with-else` in `nerves_hub_www_web/controllers/firmware_controller.ex`
2. Added catch-all error match that returns a generic error.
3. Added same error handling in `nerves_hub_api_web/controllers/firmware_controller.ex`
