### PR TITLE
Humanize display of organization info

### LINKED ISSUE #415: Display organization limits in human-readable units
**Describe the bug**
Some mental math is needed to understand the org limits right now:

image

**Expected behavior**
Display unreferenced firmware gc time in days and firmware size in MB or GB.

### PR DESCRIPTION
**Pull request by pcmarks**
Fixes #415
Show Firmware size in MiB, GiB
Show TTL in days, etc. depending on value.

### CODE REVIEW

File: apps/nerves_hub_www/lib/nerves_hub_www_web/views/org_view.ex [hunk 1]
```diff
@@ -1,3 +1,29 @@
...
+  @gib :math.pow(2, 30)
+  @mib :math.pow(2, 20)
+  @kib :math.pow(2, 10)
+  @precision 3
+
+  def humanize_ttl_seconds(seconds) do
+    seconds
+    |> Timex.Duration.from_seconds()
+    |> Timex.Format.Duration.Formatter.format(:humanized)
+  end
```
Comment (jjcarstens) [inline apps/nerves_hub_www/lib/nerves_hub_www_web/views/org_view.ex]: I think these helper functions will useful in quite a few views. I think it'd probably be better to put them in `LayoutView` or as a helper module that we can import in specific views that may want them. What do you think?

Comment (fhunleth) [reply apps/nerves_hub_www/lib/nerves_hub_www_web/views/org_view.ex]: I like that idea since it will make the code easier to unit test. I think `humanize_size` could use a couple unit tests on second look.

Comment (jjcarstens) [reply apps/nerves_hub_www/lib/nerves_hub_www_web/views/org_view.ex]: Also just throwing this out there but there is a `Size` library with a `humanize!` macro that could also handle this:
https://github.com/jfcalvo/size

Doesn't really matter to me either way. Just an FYI incase that was easier to use

Comment (pcmarks) [reply apps/nerves_hub_www/lib/nerves_hub_www_web/views/org_view.ex]: I guess I would lean towards putting them in LayoutView for now.

**Comment by fhunleth** [comment]
Looks good!
