### PR TITLE
Hex cert

### LINKED ISSUE #701: Show certificate serial number in hex to match openssl
**Describe the bug**

When inspecting certificates in NH, the serial number looks like this:

image

When using OpenSSL to dump certificates, they look like this:

```
$ openssl x509 -in cert.pem -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            4b:7d:f4:cc:2d:21:e8:58:63:de:e5:fc:c7:6f:a1:b2
...
```

It would be nice if the serial number were printed in hex to make it easier to compare. A side benefit would be that it might not wrap any more in the UI.

### PR DESCRIPTION
**Pull request by ConnorRigby**
Fixes #701

### CODE REVIEW

**Comment by jjcarstens** [comment]
What would you think about being able to click through hex and internet representation of the serial? I do have times where I want the integer value

**Comment by fhunleth** [comment]
When do you want the integer value? Perhaps those places need to be updated too.

File: apps/nerves_hub_www/lib/nerves_hub_www_web/views/org_certificate.ex [hunk 1]
```diff
@@ -2,4 +2,12 @@ defmodule NervesHubWWWWeb.OrgCertificateView do
   use NervesHubWWWWeb, :view
 
   alias NervesHubWWWWeb.LayoutView.DateTimeFormat, as: DateTimeFormat
+
+  def format_serial(big_long_integer) when is_integer(big_long_integer) do
```
Comment (fhunleth) [inline apps/nerves_hub_www/lib/nerves_hub_www_web/views/org_certificate.ex:6]: I've learned that serial numbers are converted to strings throughout NervesHub. That means this will fail. However, I really think that serial numbers should be passed around as integers since that's how the X509 library natively uses them.

Comment (jjcarstens) [reply apps/nerves_hub_www/lib/nerves_hub_www_web/views/org_certificate.ex:6]: So I'm all for this, but in order to do this we'd have to keep the serial stored in the DB as a string because some serials are too large to fit as a Postgres integer data type (which max is bigint, or int8). We'd run into something like this:

```
** (Postgrex.Error) ERROR 22003 (numeric_value_out_of_range) value "422154175989008335861639249273408275957749326847" is out of range for type integer
```

If we're okay storing as one way, but using as another, then we can do it. Though it will require that every DB query would need to be adapted to convert serials to strings on the lookup anyway. So...is it worth it?

**Review by jjcarstens — APPROVED** [review]

File: apps/nerves_hub_www/lib/nerves_hub_www_web/views/org_certificate.ex (hunk 1 above)
Comment (fhunleth) [reply apps/nerves_hub_www/lib/nerves_hub_www_web/views/org_certificate.ex:6]: I looked at the certificate handling code, and I'm more interested in catching the missing fields issue (this is #702). The "represent certificates as decimal number strings for Postgres" makes me sad, but I've lost motivation to address that.

File: apps/nerves_hub_www/lib/nerves_hub_www_web/views/org_certificate.ex [hunk 2]
```diff
@@ -2,4 +2,17 @@ defmodule NervesHubWWWWeb.OrgCertificateView do
...
+    big_long_integer
+    |> Integer.to_string(16)
+    |> to_charlist()
+    |> Enum.chunk_every(2)
+    |> Enum.join(":")
+  end
+
+  def format_serial(serial_str) when is_bitstring(serial_str) do
```
Comment (fhunleth) [inline apps/nerves_hub_www/lib/nerves_hub_www_web/views/org_certificate.ex:14]:
```suggestion
  def format_serial(serial_str) when is_binary(serial_str) do
```

File: apps/nerves_hub_www/test/nerves_hub_www_web/views/org_certificate_view_test.exs [hunk 3]
```diff
@@ -0,0 +1,9 @@
+defmodule NervesHubWWWWeb.OrgCertificateViewTest do
+  use ExUnit.Case
+  alias NervesHubWWWWeb.OrgCertificateView
+
+  test "serial number is formatted in hex" do
+    OrgCertificateView.format_serial(112_346_101_875_805_641_052_401_911_002_393_715_100) ==
```
Comment (fhunleth) [inline apps/nerves_hub_www/test/nerves_hub_www_web/views/org_certificate_view_test.exs:6]:
```suggestion
    OrgCertificateView.format_serial("112346101875805641052401911002393715100") ==
```

**Review by fhunleth — APPROVED** [review]

**Review by mobileoverlord — APPROVED** [review]
