### PR TITLE
Show helpful message when uploading duplicate firmware

### LINKED ISSUE #1473: Uploading duplicate firmware gives unfriendly error message
**Describe the bug**
When uploading a firmware build that has already been uploaded successfully, you are given a generic "Unknown error uploading firmware.
" error message rather than a more specific message saying its a duplicate. The logs show 

**To Reproduce**
1. Go to the /firmware/upload page
2. Click on the box to upload firmware
3. Select a firmware build
4. upload
5. go back to the /firmware/upload page
6. try and re upload the same firmware that you did in the previous step
7. See error `Unknown error uploading firmware.`

**Expected behavior**
A message saying this firmware has already been uploaded, so that I don't think there's something wrong with the firmware build. 

**Screenshots**
Screenshot 2024-08-27 at 9 00 10 AM

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Error logs observed:
```
16:00:59.167 [error] pid=<0.1763.0> mfa=NervesHub.Firmwares.create_firmware/3 Error while publishing firmware: #Ecto.Changeset<action: :insert, changes: %{size: 32461873, version: "1.xx", description: "xx", author: "xx", org_id: x, product_id: x, uuid: "x", platform: "x", architecture: "armx, delta_updatable: x, org_key_id: x, upload_metadata: %{"s3_key" => "firmware/x/x.fw"}}, errors: [uuid: {"has already been taken", [constraint: :unique, constraint_name: "firmwares_product_id_uuid_index"]}], data: #NervesHub.Firmwares.Firmware<>, valid?: false>
```

### PR DESCRIPTION
**Pull request by nshoes**
Fixes #1473.

This adds an error clause to provide helpful feedback when uploading firmware that has already been uploaded. [There's already a test for this constraint](https://github.com/nerves-hub/nerves_hub_web/blob/b7efd90ff828c0a6ee52b0b40ba3065cd68b6985/test/nerves_hub/firmwares_test.exs#L53), but let me know if a LiveView test is wanted/needed.

CleanShot 2024-11-01 at 08 35 36

### CODE REVIEW

File: lib/nerves_hub_web/live/firmware.ex [hunk 1]
```diff
@@ -140,6 +140,16 @@ defmodule NervesHubWeb.Live.Firmware do
...
 
+      {:error,
+       %Ecto.Changeset{
+         errors: [
+           uuid:
+             {"has already been taken",
+              [constraint: :unique, constraint_name: "firmwares_product_id_uuid_index"]}
+         ]
+       }} ->
+        error_feedback(socket, "Duplicate firmware uploads are not allowed")
```
Comment (jjcarstens) [inline lib/nerves_hub_web/live/firmware.ex:151]: Do we get the uuid back in that changeset somewhere? It would be really cool to say something like `Duplicate firmware - <link-to-firmware>`

Comment (nshoes) [reply lib/nerves_hub_web/live/firmware.ex:151]: Oh, good idea! I'll try.

Comment (nshoes) [reply lib/nerves_hub_web/live/firmware.ex]: Done! Updated the gif in the PR description.

File: lib/nerves_hub_web/live/firmware.ex [hunk 2]
```diff
@@ -140,6 +140,22 @@ defmodule NervesHubWeb.Live.Firmware do
...
+             {"has already been taken",
+              [constraint: :unique, constraint_name: "firmwares_product_id_uuid_index"]}
+         ]
+       } = c} ->
+        route =
+          "/org/#{socket.assigns.org.name}/#{socket.assigns.product.name}/firmware/#{c.changes.uuid}"
+
+        error_feedback(
+          socket,
+          "Duplicate firmware - <a href='#{route}' target='blank'>View Firmware</a>"
```
Comment (joshk) [inline lib/nerves_hub_web/live/firmware.ex:156]: I'd prefer to find a way to not include an `<a href>` in a string error message, and then also use `raw` for displaying the message.

It might require a little refactoring, eg. instead of line 164 adding an error message to the assigns, maybe we add an `error_code`, like `:duplicate_firmware` and then use a helper function in the template which uses a `case` statement to define the long form message.

**Review by joshk — CHANGES_REQUESTED** [review]

File: lib/nerves_hub_web/live/firmware.ex (hunk 2 above)
Comment (nshoes) [reply lib/nerves_hub_web/live/firmware.ex:156]: I like that a lot more, I'll implement!

Comment (nshoes) [reply lib/nerves_hub_web/live/firmware.ex]: Changes pushed. I think instead of handling this scenario in a pattern-match with `error_feedback`, it could just be handled inline since we have to pattern-match on the UUID error and then pattern-match it again which feels weird. Lmk what you think!

File: lib/nerves_hub_web/live/firmware.ex [hunk 3]
```diff
@@ -151,6 +162,20 @@ defmodule NervesHubWeb.Live.Firmware do
...
+         socket,
+         %Ecto.Changeset{errors: [uuid: {"has already been taken", _}]} = changeset
+       ) do
+    socket
+    |> assign(:error_message, "Duplicate Firmware Is Not Allowed")
+    |> assign(:error_code, :duplicate_firmware)
+    |> assign(
+      :firmware_path,
+      "/org/#{socket.assigns.org.name}/#{socket.assigns.product.name}/firmware/#{changeset.changes.uuid}"
+    )
```
Comment (jjcarstens) [inline lib/nerves_hub_web/live/firmware.ex:175]:
```suggestion
    |> assign(:error_code, {:duplicate_firmware, uuid})
```

Since we have control of this structure, we could just include the duplicate UUID and let the case handling of that view build the URL for it (or whatever else). That way we're not so coupled to 2 independent pieces of data having to exist in the assigns (`@error_code` and `@firmware_path`)

**Review by joshk — APPROVED** [review]
This generally looks good to me
